<?php
//to check if the file that includes this code is two level far from the required page or one level. 
if(file_exists("../general_backend/sessionStart.php")){
    require "../general_backend/sessionStart.php";
    require "../general_backend/conn.php";
}
elseif (file_exists("../../general_backend/sessionStart.php")){
    require "../../general_backend/sessionStart.php";
    require "../../general_backend/conn.php";
}
else{
    require "general_backend/sessionStart.php";
    require "general_backend/conn.php";
}

// initializing variables
// initializing variables
$username = "";
$password = "";
$compID = "";

// REGISTER USER
if (isset($_POST['submitRepresentative'])) {
  // receive all input values from the form
  $username = mysqli_real_escape_string($conn, $_POST['username']);
  $password = mysqli_real_escape_string($conn, $_POST['password']);
  $compID = $_SESSION['compID'];

  // form validation: ensure that the form is correctly filled ...

  // first check the database to make sure
  // a user does not already exist with the same username and/or email
  $user_check_query = "SELECT * FROM user1 WHERE username='$username' LIMIT 1";
  $result = mysqli_query($conn, $user_check_query);
  $user = mysqli_fetch_assoc($result);

  if ($user) { // if user exists

    if ($user['username'] === $username) {
      $error= "Username is already taken!";
      echo "<script type='text/javascript'>alert('$error');</script>";
      echo "<script type='text/javascript'>window.location.href = '../representatives.php';</script>";

    }
  }

  // Finally, register user if there are no errors in the form
  if ($error == "") {

  	$query = "INSERT INTO user1 (username, password, type) VALUES('$username','$password','representative');";
    mysqli_query($conn, $query);
    $last_userID = mysqli_insert_id($conn); //mysqli_insert_id this function takes last value generated by AUTO-INCREMENT.

    $query = "INSERT INTO companyrep (userID, repID, compID, type) VALUES('$last_userID', 'NULL' , '$compID', 2);";
    mysqli_query($conn, $query);

  	header('location: ../representatives.php');
  }
}
mysqli_close($conn);
?>
